version: "3.8"
# https://medium.com/@meherbensalah4/how-to-dockerize-symfony-project-f06bcd735308
services:
  # Mysql database container
  db:
    image: mysql
    container_name: fs_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - fs_network

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: fs_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - fs_network

  # Symfony apache project container
  www:
    build: .docker/php
    container_name: fs_php
    ports:
      - "8741:80"
    volumes:
      - ./.docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    depends_on:
      - db
    networks:
      - fs_network

networks:
  fs_network:

volumes:
  db-data:
